### ISSUE TITLE
фоткі-квадраты, зазор

### ISSUE THREAD

**Issue by Raman1981** [miensk-bike-tour/mienskbiketour.by#13]
на стартавых паміж фоткамі-квадратамі, якія рэпрэзентуюць экскурсіі - ёсць зазор, хаця ўсе фоткі дакладна ідэнтычныя. Прашу знайсці прычыну зазора і па магчымасці - выбравіць.

**Comment by alies-dev** [comment]
не бачу такога бага, відаць выпраўлена
